name: Publish to Exchange and Deploy to CloudHub 2.0

on:
  push:
    branches:
      - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout this repo
              uses: actions/checkout@v4

            - name: Cache dependencies
              uses: actions/cache@v4
              with:
                path: ~/.m2/repository
                key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                restore-keys: ${{ runner.os }}-maven-

            - name: Set up JDK 1.8
              uses: actions/setup-java@v4
              with:
                distribution: "zulu"
                java-version: 8

            - name: Publish to Exchange
              run: |
                mvn deploy --settings .maven/settings.xml -DskipMunitTests \
                -Dclient.id="${{ secrets.CONNECTED_APP_CLIENT_ID }}" \
                -Dclient.secret="${{ secrets.CONNECTED_APP_CLIENT_SECRET }}"

            - name: Deploy to CloudHub 2.0
              run: |
                artifactName=$(ls *.jar | head -1)
                mvn mule:deploy --settings .maven/settings.xml -DskipMunitTests \
                -Dmule.artifact=$artifactName \
                -Dclient.id="${{ secrets.CONNECTED_APP_CLIENT_ID }}" \
                -Dclient.secret="${{ secrets.CONNECTED_APP_CLIENT_SECRET }}"