name: Test with MUnit

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: 8
      - name: Test with Maven
        env:
          nexus_username: ${{ secrets.anypoint_platform_username }}
          nexus_password: ${{ secrets.NEXUS_PASSWORD }}
        run: mvn test --settings .maven/settings.xml -Dmunit.failIfNoTests=true